package NewsApp.exception;

public enum  ErrorCode
{
    ENTITY_NOT_FOUND,
    INVALID_REQUEST,
    ACCESS_DENIED,
    INTERNAL_SERVER_ERROR,
    EMAIL_ALREADY_EXISTS,
    NEWS_NOT_FOUND,
    CATEGORIES_NOT_FOUND

};

